//viewのフォームから受け取る値
export const INPUT_ID = "INPUT_ID"
export const INPUT_PASSWORD = "INPUT_PASSWORD"
export const INPUT_SEND_ADDRESS = "INPUT_SEND_ADDRESS"
export const INPUT_SEND_AMOUNT = "INPUT_SEND_AMOUNT"
export const INPUT_GET_AMOUNT = "INPUT_GET_AMOUNT"

// アカウント管理系
export const ACCOUNT_SIGN_IN = "ACCOUNT_SIGN_IN"
export const ACCOUNT_SIGN_UP = "ACCOUNT_SIGN_UP"
export const ACCOUNT_SIGN_OUT = "ACCOUNT_SIGN_OUT"
export const ACCOUNT_UNLOCK = "ACCOUNT_UNLOCK"
export const ACCOUNT_CHANGE_PROFILES = "ACCOUNT_CHANGE_PROFILES" //そのうち実装するはず

// 画面遷移に使うフラグ系
export const SIGNIN_SUCCESSED = "SIGNIN_SUCCESSED"
export const SIGNIN_CLOSED = "SIGNIN_CLOSED"
export const ACCOUNT_CREATED = "ACCOUNT_CREATED"
export const JUNP_TO_SIGNIN = "JUNP_TO_SIGNIN"
export const JUNP_TO_SIGNUP = "JUNP_TO_SIGNUP"

// 健康コイン系
export const HTC_SEND = "HTC_SEND"
export const HTC_GET = "HTC_GET"
export const HTC_GET_BALANCE = "HTC_GET_BALANCE"

//fitbit
export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMkQ5NDgiLCJzdWIiOiI2WDU1OTgiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyc29jIHJhY3QgcnNldCBybG9jIHJ3ZWkgcmhyIHJwcm8gcm51dCByc2xlIiwiZXhwIjoxNTM5ODU1OTMxLCJpYXQiOjE1Mzk2NzMzNDZ9.PxYOhz7dFnOXADcohRU2e8VJWoLiL6o_A4H3jnRYsVQ"
export const GET_DAILY_SUMMARY = "GET_DAILY_SUMMARY"
export const GOALS = "GOALS"
export const SUMMALY = "SUMMARY"
export const ACHIEVEMENTS_RESET = "ACHIEVEMENTS_RESET"
export const ACHIEVEMENT_DONE = "ACHIEVEMENT_DONE"
